Add `bento` to the list of Deployment tools
nix-community/awesome-nix pull request #148
Opened 2023-01-29 15:15 UTC by anoadragon453

Adds [bento](https://github.com/rapenne-s/bento/) - yet another tool to deploy your nix systems.

cc @rapenne-s

2023-01-29 16:54 UTC, Mic92 approved these changes

2023-01-29 20:27 UTC, rapenne-s approved these changes
thanks! looks good to me

2023-01-29 23:46 UTC, houstdav000 requested changes
Looks good, but could be better. Check the comment for info

2023-01-29 23:46 UTC, houstdav000 commented on README.md
> +* [bento](https://github.com/rapenne-s/bento/) - A KISS deployment tool to keep your NixOS fleet (servers & workstations) up to date.
The tool itself looks pretty cool and continually developed, so its probably good to add.

As a nitpick, trim the last slash from the URL please.

More seriously, the given description doesn't do a great job of making it distinct from the other deployment tools. I'd recommend mentioning it's pull-based and that it leverages SSH.

Perhaps something like "A pull-based deployment agent to keep your NixOS fleet up-to-date over SSH."?

2023-01-29 23:47 UTC, houstdav000 commented
I'll take a look when I get home about that API limit GitHub Action failure

2023-02-20 16:16 UTC, Mic92 commented
> I'll take a look when I get home about that API limit GitHub Action failure

Should fixed now?

2023-02-20 18:39 UTC, houstdav000 commented
Should be. Both the number of requests should have been reduced with the version upgrade, and the token should lift our request limit. I'll verify in a second though

2023-02-20 20:04 UTC, Mic92 approved these changes

2023-02-21 03:43 UTC, houstdav000 commented
I'd still personally like the description clarified as with that review I left, but I suppose it may work as is

2023-02-25 20:17 UTC, houstdav000 approved these changes
Thought I made that a review. Here we go

2023-02-25 20:17 UTC, merged