add Runix to development tools section
nix-community/awesome-nix pull request #152
Opened 2023-02-13 15:25 UTC by jurraca

[Runix](https://github.com/flox/runix) is a typesafe Rust interface to the Nix CLI.

2023-02-13 18:14 UTC, houstdav000 commented
Looks a little too new to me at 2 weeks old, and with that warning about an unstable API. If it's up and working though with good coverage in a few weeks, it could be interesting though.

Additionally, it might be worth specifying it's a Rust development library instead of an application in the proposed description.

2023-03-10 12:38 UTC, houstdav000 requested changes
Could use some minor changes and probably a move to the "Programming Languages" section under "Rust"

2023-03-10 12:38 UTC, houstdav000 commented on README.md
> +* [runix](https://github.com/flox/runix) - A typesafe Rust interface to the nix CLI.
Capitalize Nix please.

I kinda wonder if this should go in the "Rust" subsection of "Programming Languages", since it's a library crate...

2023-03-10 12:38 UTC, houstdav000 commented on README.md
> -* [Makes](https://github.com/fluidattacks/makes) - A Nix-based CI/CD pipeline framework for building, testing, and releasing projects in any language, from anywhere.
Did this line have a trailing space? Not seeing the change personally...

2024-03-04 14:52 UTC, cyntheticfox commented
Repository now has a comment that its not maintained on the README, so closing pull request. If that changes in the future and the entry is good, I'd still be interested to add it

2024-03-04 14:52 UTC, closed without merging