Add Amos's guide to build a Rust service
nix-community/awesome-nix pull request #176
Opened 2023-05-31 22:13 UTC by alper

A lot of Rust but also a very thorough treatment of a lot of parts of Nix.

2023-05-31 23:55 UTC, cyntheticfox requested changes
Wording could use some grammatical changes, but otherwise looks good.

2023-05-31 23:55 UTC, cyntheticfox commented on README.md
> +* [Building a Rust service with Nix](https://fasterthanli.me/series/building-a-rust-service-with-nix) - About creating a Rust application but treats a lot of Nix as well and is *very* thorough.
```suggestion
* [Building a Rust service with Nix](https://fasterthanli.me/series/building-a-rust-service-with-nix) - An in-depth blog series about creating a Rust application with Nix.
```

2023-06-02 10:13 UTC, alper commented
Applied suggestions.

2023-06-02 11:07 UTC, cyntheticfox approved these changes
Looks good

2023-06-02 11:07 UTC, merged