Add nix-output-monitor
nix-community/awesome-nix pull request #181
Opened 2023-06-08 17:09 UTC by j4m3s-s

Add link to another nix tool

2023-06-08 22:22 UTC, cyntheticfox requested changes
Word choice recommendation is optional, but please move the entry up one line to before `nix-prefetch` to maintain alphabetical ordering

2023-06-08 22:22 UTC, cyntheticfox commented on README.md
> +* [nix-output-monitor](https://git.maralorn.de/nix-output-monitor/) - A tool to get additional information while building.
```suggestion
* [nix-output-monitor](https://git.maralorn.de/nix-output-monitor/) - A tool to produce useful graphs and statistics when building derivations.
```

The original description is correct, both factually and grammatically, but kinda undersells the tool, so I'd recommend the above word choice, but that's up to you.

2023-06-09 17:20 UTC, j4m3s-s commented
And here I thought I did it alphabetically ...
Fixed it. I used your description which is more descriptive of the tool, thanks for the suggestion.

2023-06-17 13:43 UTC, cyntheticfox approved these changes
Looks good now

2023-06-17 13:43 UTC, merged