Feat: SnowflakeOS
nix-community/awesome-nix pull request #248
Opened 2024-08-12 10:26 UTC by Malix-off

2024-08-12 10:29 UTC, Malix-off commented
[Would probably be better bellow SnowflakeOS](https://github.com/nix-community/awesome-nix/pull/248)

2024-08-13 10:25 UTC, cyntheticfox requested changes
Dont know why it left two line comments -- probably a GitHub android app bug.

Fix the minor punctuation thing and its good to merge IMO

2024-08-13 10:25 UTC, cyntheticfox commented on README.md
> +* [SnowflakeOS](https://snowflakeos.org/) - A NixOS based Linux distribution focused on beginner friendliness and ease of use.
```suggestion
* [SnowflakeOS](https://snowflakeos.org/) - A NixOS-based Linux distribution focused on beginner friendliness and ease of use.
```

I do have to wonder what a NixOS cringe distro would look like :sweatsmile:

2024-08-13 10:25 UTC, cyntheticfox commented on README.md
> +* [SnowflakeOS](https://snowflakeos.org/) - A NixOS based Linux distribution focused on beginner friendliness and ease of use.
```suggestion
* [SnowflakeOS](https://snowflakeos.org/) - A NixOS-based Linux distribution focused on beginner friendliness and ease of use.
```

I do have to wonder what a NixOS cringe distro would look like :sweatsmile:

2024-08-13 11:08 UTC, cyntheticfox approved these changes
Looks good with the edit!

2024-08-13 11:11 UTC, merged