add npins
nix-community/awesome-nix pull request #257
Opened 2024-10-13 19:01 UTC by phanirithvij

2024-10-18 19:28 UTC, cyntheticfox requested changes

2024-10-18 19:28 UTC, cyntheticfox commented on README.md
> +* [npins](https://github.com/andir/npins) - npins is a simple tool for handling different types of dependencies in a Nix project. It is inspired by and comparable to Niv.
```suggestion
* [npins](https://github.com/andir/npins) - A simple tool for handling different types of dependencies in a Nix project. It is inspired by and comparable to Niv.
```

To make the linter happy

2024-10-21 18:31 UTC, cyntheticfox approved these changes
looks good now. provided the linters pass, will merge

2024-10-22 02:58 UTC, phanirithvij commented
Can the lint step be made to run without maintainers approval?

2024-10-22 09:08 UTC, Mic92 commented
It's a repository setting. Since I don't expect too much spam on this repository probably a good idea.

2024-10-22 11:16 UTC, merged

2024-10-22 11:20 UTC, cyntheticfox commented
Afaict, you can't turn it off entirely, but I did loosen it to only require approval for first-time contributes with new github accounts (from all first-time contributors)