add crystal2nix and colmena
nix-community/awesome-nix pull request #75
Opened 2021-03-30 10:40 UTC by peterhoeg

2021-03-30 14:22 UTC, houstdav000 requested changes
In the future, I'd recommend keeping entries separated mostly for ease of review (and ease of merging), but two is manageable.

I'd recommend slight changes to the entries for formatting consistency, but otherwise they're good.

As for the projects, Colmena looks pretty fleshed out, while I think crystal2nix might best add some to the `README.md`, particularly on the usage (what the command will do) and examples.

2021-03-30 14:22 UTC, houstdav000 commented on README.md
> +* [crystal2nix](https://github.com/nix-community/crystal2nix) - Convert shard.lock into Nix expressions.
Add backticks/grave symbols around "shard.lock" for formatting consistency with other filenames like `poetry.lock`.

2021-03-30 14:22 UTC, houstdav000 commented on README.md
> +* [colmena](https://github.com/zhaofengli/colmena) - A simple, stateless NixOS deployment tool modeled after NixOps and morph.
Since [the project](https://github.com/zhaofengli/colmena) capitalizes "Colmena", we should too. Otherwise, looks good!

2021-03-31 00:12 UTC, peterhoeg commented
> while I think crystal2nix might best add some to the README.md, particularly on the usage (what the command will do) and examples.

There's quite a few things that will be added to this over the next couple of weeks - documentation is one of them.

2021-03-31 09:19 UTC, houstdav000 approved these changes

2021-03-31 14:23 UTC, merged